#!/bin/bash

echo "🔧 Fixing Firestore profile issue..."
echo ""
echo "⚠️  STEP 1: Apply Firebase Rules"
echo "   1. Go to: https://console.firebase.google.com"
echo "   2. Select project: seven-3efe8"
echo "   3. Go to Firestore Database → Rules"
echo "   4. Replace ALL rules with:"
echo ""
echo "rules_version = '2';"
echo "service cloud.firestore {"
echo "  match /databases/{database}/documents {"
echo "    match /{document=**} {"
echo "      allow read, write: if request.auth != null;"
echo "    }"
echo "  }"
echo "}"
echo ""
echo "   5. Click Publish"
echo "   6. Wait 30 seconds"
echo ""
echo "🚀 STEP 2: Run this after applying rules:"
echo "   node scripts/fixUserProfile.js"
echo ""
echo "✅ STEP 3: Test at:"
echo "   http://localhost:3004/test-auth"